### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ChristianFrisson** [libmapper/webmapper#29]
Hi @malloch,

What is the license of webmapper? Would it make sense to add a license?

Kind regards,
Christian

**Comment by malloch** [comment]
Hi @ChristianFrisson – I'm surprised we don't already have a license in here, thanks for bringing this up!

Attention contributors! @radarsat1, @mysteryDate, @jonwila, @DocSunset, @johnty, @peacheym, @mathiasbredholt, @bboettcher3, @napopa, @ChristianFrisson.

Can we agree on LGPL 2.1 as the license since that is required for libmapper anyway?

**Comment by DocSunset** [comment]
Affirmative!

**Comment by mathiasbredholt** [comment]
Sounds great!

**Comment by malloch** [comment]
I'll update this list as responses come in.

- [x] @ChristianFrisson
- [x] @malloch
- [ ] @radarsat1
- [ ] @mysteryDate
- [ ] @jonwila
- [x] @DocSunset
- [ ] @johnty
- [x] @peacheym
- [x] @mathiasbredholt
- [ ] @bboettcher3
- [ ] @napopa

**Comment by mysteryDate** [comment]
Sounds good to me!

**Comment by jonwila** [comment]
Sure!

**Comment by bboettcher3** [comment]
Sounds good!

**Comment by johnty** [comment]
Sure :)

**Comment by malloch** [comment]
Thanks all – as agreed by all contributors the license is now LGPL 2.1.
